# Generated by Django 6.0.4 on 2026-05-12 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN', 'Login realizado'), ('LOGIN_FALHA', 'Falha de login'), ('LOGOUT', 'Logout realizado'), ('ACESSO', 'Acesso a página'), ('CRIACAO', 'Criação de registro'), ('EDICAO', 'Edição de registro'), ('EXCLUSAO', 'Exclusão de registro')], max_length=20, verbose_name='Tipo de Evento')),
                ('matricula_tentativa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Matrícula (tentativa)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data'],
            },
        ),
    ]
