# Generated by Django 6.0.4 on 2026-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditorialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrador',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_almoxarife',
            field=models.BooleanField(default=False, verbose_name='Almoxarife'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_secretario',
            field=models.BooleanField(default=False, verbose_name='Secretário'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_solicitante',
            field=models.BooleanField(default=False, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tecnico',
            field=models.BooleanField(default=False, verbose_name='Técnico'),
        ),
    ]
