# Generated by Django 6.0.4 on 2026-06-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_administrador_user_is_almoxarife_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SO', 'Solicitante'), ('SE', 'Secretário'), ('AL', 'Almoxarife'), ('TE', 'Técnico'), ('AD', 'Administrador')], max_length=2, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='perfis',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.perfilusuario', verbose_name='Perfis'),
        ),
    ]
