# Generated by Django 6.0.4 on 2026-05-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_estoque_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de interação na categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('quantidade_minima', models.PositiveIntegerField(default=0, verbose_name='Quantidade Mínima')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro')], default='UN', max_length=2, verbose_name='Unidade de Medida')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('marca', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Série')),
                ('patrimonio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Patrimônio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_edicao', models.DateTimeField(auto_now=True, verbose_name='Última edição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_estoque', to='estoque.categoriaitem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_estoque_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de interação no item')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='estoque/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('ordem', models.IntegerField(db_index=True, default=0)),
                ('is_principal', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='estoque.itemestoque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_imagem_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de interação na imagem')),
            ],
            options={
                'verbose_name': 'Imagem do item',
                'verbose_name_plural': 'Imagens dos itens',
                'ordering': ['ordem', 'id'],
                'unique_together': {('produto', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EN', 'Entrada'), ('SA', 'Saída')], max_length=2, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.itemestoque')),
                ('protocolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='chamados.chamado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de interação na movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
                'indexes': [models.Index(fields=['item', 'data_movimentacao'], name='estoque_mov_item_id_28db9a_idx')],
            },
        ),
    ]
