# Generated by Django 5.2.13 on 2026-05-12 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamado_tecnico'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('urgencia', models.CharField(choices=[('NO', 'Normal'), ('UR', 'Urgente')], default='NO', max_length=2, verbose_name='Urgência')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_pecas', to='chamados.chamado', verbose_name='Chamado (OS)')),
                ('item_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='estoque.itemestoque', verbose_name='Item solicitado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_pecas_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que requisitou')),
            ],
            options={
                'verbose_name': 'Requisição de Peça',
                'verbose_name_plural': 'Requisições de Peças',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
