# Generated by Django 6.0.4 on 2026-04-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categoriaitem_descricao_alter_itemestoque_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaitem',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='itemimagem',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Imagem do item', 'verbose_name_plural': 'Imagens dos itens'},
        ),
    ]
