# Generated by Django 6.0.4 on 2026-06-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_requisicaopeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaopeca',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('AP', 'Aprovada'), ('RE', 'Rejeitada')], default='PE', max_length=2, verbose_name='Status'),
        ),
    ]
