# Generated by Django 6.0.4 on 2026-04-22 16:31

import apps.chamados.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(default=apps.chamados.models.gerar_protocolo, editable=False, max_length=12, unique=True, verbose_name='Protocolo')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('urgencia', models.CharField(choices=[('NO', 'Normal'), ('UR', 'Urgente')], default='NO', max_length=2, verbose_name='Urgência')),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('EA', 'Em andamento'), ('FI', 'Finalizado')], default='AB', max_length=2, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de abertura')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AlteracaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da alteração')),
                ('status_anterior', models.CharField(choices=[('AB', 'Aberto'), ('EA', 'Em andamento'), ('FI', 'Finalizado')], max_length=2, verbose_name='Status anterior')),
                ('status_novo', models.CharField(choices=[('AB', 'Aberto'), ('EA', 'Em andamento'), ('FI', 'Finalizado')], max_length=2, verbose_name='Status novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Alteração de chamado',
                'verbose_name_plural': 'Alterações de chamados',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='ItemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Item do chamado',
                'verbose_name_plural': 'Itens dos chamados',
            },
        ),
    ]
