# Generated by Django 6.0.4 on 2026-04-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('AB', 'Aberto'), ('EA', 'Em Andamento'), ('FI', 'Finalizado')], default='AB', max_length=2, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_edicao', models.DateTimeField(auto_now=True, verbose_name='Última edição')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AlteracaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Alteração')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('status_anterior', models.CharField(choices=[('AB', 'Aberto'), ('EA', 'Em Andamento'), ('FI', 'Finalizado')], max_length=2, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('AB', 'Aberto'), ('EA', 'Em Andamento'), ('FI', 'Finalizado')], max_length=2, verbose_name='Status Novo')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Alteração de Chamado',
                'verbose_name_plural': 'Alterações de Chamados',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='ItemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Item do Chamado',
                'verbose_name_plural': 'Itens dos Chamados',
            },
        ),
    ]
