# Generated by Django 6.0.4 on 2026-05-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamados', '0001_initial'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alteracaochamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_alteracoes_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de interação na alteração'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de interação'),
        ),
        migrations.AddField(
            model_name='alteracaochamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='itemchamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='chamados.chamado'),
        ),
        migrations.AddField(
            model_name='itemchamado',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='estoque.itemestoque'),
        ),
        migrations.AddField(
            model_name='itemchamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_item_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de interação no item'),
        ),
        migrations.AlterUniqueTogether(
            name='itemchamado',
            unique_together={('chamado', 'item')},
        ),
    ]
