# Generated by Django 6.0.4 on 2026-04-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='para_onde_solicitou',
            field=models.CharField(default='Não informado', max_length=200, verbose_name='Para onde solicitou:'),
        ),
    ]
