# Generated by Django 6.0.4 on 2026-04-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamado_para_onde_solicitou'),
        ('estoque', '0002_categoriaitem_descricao_alter_itemestoque_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchamado',
            options={},
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_prevista',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data prevista'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solicitante',
            field=models.CharField(help_text='Nome do solicitante ou órgão', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='itemchamado',
            unique_together={('chamado', 'item')},
        ),
    ]
