# Generated by Django 6.0.4 on 2026-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_alter_itemchamado_options_chamado_data_prevista_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemchamado',
            options={'verbose_name': 'Item do chamado', 'verbose_name_plural': 'Itens do chamado'},
        ),
        migrations.AddField(
            model_name='chamado',
            name='ultima_edicao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última edição'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='para_onde_solicitou',
            field=models.CharField(max_length=200, verbose_name='Para onde solicitou'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='solicitante',
            field=models.CharField(help_text='Nome do solicitante ou órgão', max_length=200, verbose_name='Solicitante'),
        ),
    ]
